import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/components/CommonHeader/CommonHeader";
import { WalletProvider } from "@/contexts/WalletContext";
import { ThemeProvider } from '@mui/material/styles'
import theme from '../theme/theme';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <ThemeProvider theme={theme}>
          <WalletProvider>
              <Header />
              {children}
          </WalletProvider>
      </ThemeProvider>
      </body>
    </html>
  )
}
